# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WZB696_vbsYteMTpFrv4tRxhVgbEJF24
"""

# dashboard_kpis.py

import streamlit as st
import pandas as pd
import plotly.express as px

# Título
st.set_page_config(layout="wide")
st.title("📊 Dashboard Interactivo de Ventas Comex")

# Cargar archivo
archivo_excel = "ventas_encabezado.xlsx"
df_dict = pd.read_excel(archivo_excel, sheet_name=None)

# Recorrer todas las hojas del Excel
for nombre_hoja, df in df_dict.items():
    st.markdown(f"## {nombre_hoja}")

    # Mostrar tabla
    st.dataframe(df)

    # Graficar si tiene columnas suficientes
    columnas = df.columns.tolist()
    if len(columnas) >= 2:
        # Detectar columnas numéricas
        columnas_numericas = df.select_dtypes(include='number').columns
        if len(columnas_numericas) > 0:
            fig = px.bar(
                df,
                x=columnas[0],
                y=columnas_numericas,
                barmode="group",
                title=f"Gráfica - {nombre_hoja}"
            )
            st.plotly_chart(fig, use_container_width=True)